#!/usr/bin/env bash

env | grep -i npm_package_bin | while read bin_env; do

  if [[ "$bin_env" =~ npm_package_bin* ]]; then

    IFS='=' read -a bin_env_parts <<< "$bin_env"
    executable_name=$(echo ${bin_env_parts[0]} | sed 's/npm_package_bin_//')

    # if it is a global install
    if [ "$npm_config_global" = "true" ] && [ "$executable_name" != "" ]; then
      asdf shim nodejs .npm/bin/$executable_name
    fi

  fi

done
